#pragma once

/**
 * @file modules.h
 * @brief Unified header for all EasyWork node modules
 *
 * Each node module is self-contained with:
 * - Node class definition (inherits from TypedInputNode/TypedFunctionNode)
 * - Factory registration macro (EW_REGISTER_NODE)
 * - Parameter extraction logic (auto-generated by macro)
 *
 * Available Nodes:
 * - NumberSource: Emits an integer sequence
 * - MultiplyBy: Multiplies integers by a factor
 * - PrefixText: Adds a prefix to strings
 * - IntToText: Converts integers to strings
 * - PairEmitter: Emits (int, string) tuples
 * - PairJoiner: Joins int/string pairs into one string
 * - SmallTrackedSource/SmallTrackedConsumer: SBO safety check
 *
 * Usage:
 *   #include "runtime/modules.h"  // Include all modules
 *   or
 *   #include "runtime/module/example_typed_nodes.h"  // Include specific module
 */

#include "module/example_typed_nodes.h"
