#pragma once

/**
 * @file modules.h
 * @brief Unified header for all EasyWork node modules
 *
 * Each node module is self-contained with:
 * - Node class definition (inherits from InputNode or FunctionNode)
 * - Factory registration macro (EW_REGISTER_NODE, EW_REGISTER_NODE_1, etc.)
 * - Parameter extraction logic (auto-generated by macro)
 *
 * Available Nodes:
 * - CameraSource: Captures frames from camera or mock mode
 * - CannyFilter: Applies Canny edge detection
 * - NullSink: Consumes frames without side effects (for testing)
 * - VideoWriterSink: Writes frames to video file
 * - PyFuncNode: Wraps Python callable (manual binding, not in factory)
 *
 * Usage:
 *   #include "runtime/modules.h"  // Include all modules
 *   or
 *   #include "runtime/module/camera_source.h"  // Include specific module
 */

#include "module/camera_source.h"
#include "module/canny_filter.h"
#include "module/null_sink.h"
#include "module/video_writer_sink.h"
#include "module/pyfunc_node.h"

// New type system example nodes
#include "module/example_typed_nodes.h"
